added styling for card
sanjitsarkar/xendesign pull request #5
Opened 2022-02-11 15:53 UTC by sanjitsarkar

Added styling for card component.

2022-02-11 19:09 UTC, pankaj-prog requested changes

2022-02-11 19:09 UTC, pankaj-prog commented on css/components/card/index.css
> +    border-radius: var(--br-radius);
removed commented styles

2022-02-11 19:09 UTC, pankaj-prog commented on css/components/card/index.css
> +  }
improve the indentation

2022-02-11 19:09 UTC, pankaj-prog commented on css/components/card/index.css
> +    }
you can use px for such small units

2022-02-11 19:12 UTC, sanjitsarkar commented on css/components/card/index.css
> +    }
Okay I will fix that.

2022-02-11 20:40 UTC, PrashanthreddyAinala reviewed
Rest all the code looks great

2022-02-11 20:40 UTC, PrashanthreddyAinala commented on css/components/avatar/index.css
> +    top:0%;
Just 0 will also fine no need of %.

2022-02-11 20:40 UTC, PrashanthreddyAinala commented on css/components/button/index.css
> +
use variable colors

2022-02-11 20:40 UTC, PrashanthreddyAinala commented on css/reset.css
> +}
same here for color

2022-02-11 20:40 UTC, PrashanthreddyAinala commented on css/util/color/index.css
> +}
In this complete file avoid using important, that should be the last preference.

2022-02-12 11:41 UTC, pankaj-prog approved these changes

2022-02-12 11:44 UTC, deekshithmd commented on css/components/card/index.css
> +  padding: 0.5rem;
use px for small value

2022-02-12 11:45 UTC, deekshithmd commented on css/components/card/index.css
> +  border-radius: 0 0 0.125rem 0.125rem;
for border radius use px

2022-02-12 11:45 UTC, deekshithmd approved these changes

2022-02-12 14:28 UTC, merged